                UIDocument uidoc = uiapp.ActiveUIDocument;
                Document doc = uidoc.Document; // myListView_ALL_Fam_Master.Items.Add(doc.GetElement(uidoc.Selection.GetElementIds().First()).Name);

                using (Transaction y = new Transaction(doc, "Foreach on each wall type."))
                {
                    y.Start();
                    List<ElementId> myFEC_Walls = new FilteredElementCollector(doc).OfCategory(BuiltInCategory.OST_Walls).WhereElementIsNotElementType().Where(x => x.get_Parameter(BuiltInParameter.ALL_MODEL_INSTANCE_COMMENTS).AsString() == "Example 2 Walls").Select(x => x.Id).ToList();
                    if (myFEC_Walls.Count != 0)
                    {
                        doc.Delete(myFEC_Walls);
                    } else
                    {
                        ///                  TECHNIQUE 2 OF 19
                        ///↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓ ONE OF EACH WAL L↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓

                        FilteredElementCollector myFEC_WallTypes = new FilteredElementCollector(doc).OfCategory(BuiltInCategory.OST_Walls).WhereElementIsElementType();

                        double myX = 0;
                        Element myLevel = new FilteredElementCollector(doc).OfCategory(BuiltInCategory.OST_Levels).WhereElementIsNotElementType().First();

                        foreach (ElementId myElementID in myFEC_WallTypes.ToElementIds())
                        {
                            // Create a geometry line in Revit application
                            XYZ startPoint = new XYZ(myX, 0, 0);
                            XYZ endPoint = new XYZ(myX, 10, 0);
                            Line geomLine = Line.CreateBound(startPoint, endPoint);

                            Wall myWall = Wall.Create(doc, geomLine, myElementID, myLevel.Id, 10, 0, false, false);
                            myWall.get_Parameter(BuiltInParameter.ALL_MODEL_INSTANCE_COMMENTS).Set("Example 2 Walls");

                            myX = myX + 3;
                        }
                        ///↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑
                    }

                    y.Commit();
                }